### ISSUE TITLE
Custom location

### ISSUE THREAD

**Issue by EvertJob** [jc21/nginx-proxy-manager#1027]
Hi,

Maybe someone can help me.

I'm running Nginx Proxy and it works fine. The only problem: I'm running Pi-Hole on port 82 and I cannot get it working.
The URL I need to use for the admin is: http://192.168.1.254:82/admin. I would like to connect to pihole.domain.ext.

I've tried everything as far as I can see, can someone help me?

<img width="535" alt="Screenshot 2021-04-18 at 20 03 53" src="https://user-images.githubusercontent.com/58138839/115155640-35df8b00-a081-11eb-967c-a9783aa30ded.png">
<img width="531" alt="Screenshot 2021-04-18 at 20 04 12" src="https://user-images.githubusercontent.com/58138839/115155663-40018980-a081-11eb-8222-f2c0775dfbfd.png">

**Comment by dgsharpe** [comment]
Check out these instructions posted by @jc21 in #104 and make sure you've followed them exactly:

>1. Create a proxy host
>2. On the details tab, enter any ip address and port, it's required for the form but it won't actually be used, so it can be anything
>3. On the Custom Locations tab, create a location with / as the location path and for the Forward Hostname / IP enter 192.168.0.10/phpmyadmin/ making sure you have that trailing slash, it's important.
>4. Save, and test.

In particular, it looks like you might have not included the trailing slash in step 3.

However, this Github issues page isn't really for community support, it's for reporting bugs - if you're looking for assistance with your setup, you'll be better off [checking out the Reddit community.](https://www.reddit.com/r/nginxproxymanager/)

**Comment by 3Dscrewer** [comment]
That’s not a bug, that happens not reading the manuals. The use of custom location is totally wrong. The custom location is needed if your pi-hole is in a subfolder. The standard installation is not. You have simply to use the IP, I guess raspberry, and the port. You must see a page like the picture, click at the blue colored sentence and you’re ready

![346FBA4C-2033-4E86-9037-381FF65ADAD6](https://user-images.githubusercontent.com/34925249/115359899-675e7080-a1bf-11eb-9ee4-c1094f91b37e.png)

**Comment by 3Dscrewer** [comment]
@EvertJob Sorry for that reading the manual, but Google is still your friend. I don’t use Pi-Hole over the Net, but I’m interested in this case.
So the path to the admin page is /var/www/html/admin. So the custom path is /html/admin/ because in /html is only the landing page like picture above.
The Web access doesn’t work at all, because Pi-hole is refusing the access. It is showing that picture, ok, whitelist and again, no access.
And here comes Google.

So one possible way .... I didn’t try, because I don’t need that.
at /root/npm/data/nginx/proxy_host/ you will find 
1.conf
2.conf
depending how many domains you have.
There you must find your domain, it is mentioned at the Top.
Copy necessary parts of the Pi-Hole site into that x.conf and it should work ... I guess 😉

Sorry for that, but is a security reason by Pi-hole.



![3EEC73A1-8BB6-4FF5-963C-B855EB88F247](https://user-images.githubusercontent.com/34925249/115542479-9bf62900-a2a0-11eb-836f-9a1839e29bb7.jpeg)

**Comment by EvertJob** [comment]
@3Dscrewer Thanks. But the issue is now fixed. The last / was missing.
