### ISSUE TITLE
Luadns error

### ISSUE THREAD

**Issue by drx1x2** [jc21/nginx-proxy-manager#1119]
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

[5/24/2021] [9:03:31 AM] [Nginx ] › ℹ info Reloading Nginx
[5/24/2021] [9:03:31 AM] [Express ] › ⚠ warning Command failed: /opt/certbot/bin/certbot certonly --non-interactive --cert-name "npm-10" --agree-tos --email "mymail@gmail.com" --domains "domain" --authenticator dns-luadns --dns-luadns-credentials "/etc/letsencrypt/credentials/credentials-10" --dns-luadns-propagation-seconds 120

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-luadns, Installer None
Performing the following challenges:
dns-01 challenge for domain.com
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:

need help

**Comment by chaptergy** [comment]
This is an [issue with certbot](https://github.com/certbot/certbot/pull/8819). There is nothing we can do about that. We'll habe to wait until a new version oft certbot is available, and then redeploy the npm container vor manually update certbot inside the container.

**Comment by gitmors** [comment]
Fix the file .../certbot/plugins/dns_common_lexicon.py

Change the argument name type with rtype line 48 :

        self.provider.create_record(rtype='TXT', name=record_name, content=record_content)
and line 70 :

        self.provider.delete_record(rtype='TXT', name=record_name, content=record_content)

**Comment by spennell** [comment]
I can confirm @gitmors solution works. I was facing a similar issue when trying to configure certs for DNSimple.

**Comment by Trollwut** [comment]
Hey mates!

Can confirm that this solution also works for me. So yes, we have to wait for `certbot` having this fixed, but as a workaround, one can do it quite simply.

Just adding this information for newcomers with the same problem.

If you have your NPM dockered, go into your container like this:

    docker-compose exec nginx-proxy bash

Then you might need some kind of text editor, install it like:

    apt update && apt install vim

Substitute with your editor of choice.

Then locate the `certbot` library and open that file in your text editor (check the folder twice, it might have another location for you):

    vim /opt/certbot/lib/python3.7/site-packages/certbot/plugins/dns_common_lexicon.py

*(If it's not there, you can check for its location with command `find / -type f -name "dns_common_lexicon.py"`)*

In this file, edit it like @gitmors told us in [this comment](https://github.com/jc21/nginx-proxy-manager/issues/1119#issuecomment-850954344).

Save and exit.

It should be working by now. But it *could* be that your `certbot` has exited due to the error and hasn't deleted it's lockfiles (which will prevent it from running again).

You can see if you have lock files on your system:

    find / -type f -name ".certbot.lock" -exec rm {} \;

**Please doublecheck if only files are listed that you really don't want!**

You can delete them with that:

    find / -type f -name ".certbot.lock" -exec rm {} \;

Now, exit your docker shell, go to NPM webpage and try to get your new DNS certificate. :)
