### ISSUE TITLE
How to use it with a generic provider with DNS TXT records?

### ISSUE THREAD

**Issue by kosuodhmwa** [jc21/nginx-proxy-manager#1143]
Hi

How to use Nginx Proxy Manager with round robin DNS A-Record when i want to get a Let's Encrypt certificate? What to select in the DNS Challenge Provider select box? There are 2 generic entries: 1.) Something with `rfc` and the entry on list bottom called `DNS-ACME`...

Now:

a.) What to to when i have another provider the the ones they are in that list? Using the `rfc` method or `DNS-ACME`...?

AND

b.) Are DNS TXT-Record the correct record type to handle that issue

I can't find a step-by-step guide to realize that - and i also read that this part was removed from the Lets Encrypt documentation: https://serversupportforum.de/threads/lets-encrypt-zertifikat-ausstellen-wenn-dns-round-robin-verwendet-wird.60226/

Thank you very very much for your feedbacks!! :-)

**Comment by kosuodhmwa** [comment]
Is that possible what i want or not?

**Comment by chaptergy** [comment]
I do not know much about the two generic providers either. Maybe you will find useful information on the documentation of [certbot-dns-acmedns](https://pypi.org/project/certbot-dns-acmedns/) and [certbot-dns-rfc2136](https://certbot-dns-rfc2136.readthedocs.io/en/stable/).

But generally DNS challenges is what you need. If you have your domains at a provider, which is not listed, you can visit pypi.org, and search for a package with the name `certbot-dns-<privider>`. If such a package exists, you can open an issue requesting this package to be listed in the dropdown. If such a package does not exist, I'm afraid you won't be able to use NPM to solve the DNS challenge for you.

**Comment by kosuodhmwa** [comment]
Hello 

Thank you very much for your feedback. It's just a "plain vanilla" DNS provider (the same company where the domains was bought)

Am i wrong when i think it's pissible with EVERY dns provider and (the corrrect) DNS TXT records...?

**Comment by chaptergy** [comment]
It is usually the case that your domain provider is also your DNS provider.

Yes and no. Certbot does in theory allow manual DNS challenges, where you manually create the record, which is compatible with every DNS provider, which lets you edit the records. However this is [not available through NPM](https://github.com/jc21/nginx-proxy-manager/issues/813). Also in practice, since a LetsEncrypt certificate expires after 3 months, it should be renewed every 2 months. So every 2 months you would have to manually add a specific TXT record to your domain for your certificate to continue working. This is why this is not officially recommended by certbot.

That is why NPM only support DNS providers which have an API though which you can set this record, so all this can be done automatically.

**Comment by jayjupdhig** [comment]
Thank you very much!! :-)

**Comment by kosuodhmwa** [comment]
OK, thx, will close the issue now...
