### ISSUE TITLE
Question re: "For future stability, please consider using 2.9.3 tag"?

### ISSUE THREAD

**Issue by johntdavis84** [jc21/nginx-proxy-manager#1193]
Hello,

I hope you're doing well. I had a question about the tags. I've been using the "latest" tag for quite a while, and I noticed the above message after my last update.

If I switch to the 2.9.3 tag, will I stop getting new updates until 3.0 comes out, or will I still get bugfixes releases?

I just noticed a new update available on the latest tag within the last few days, so I'm not sure exactly what's going on.

Thanks!

**Comment by l4rm4nd** [comment]
It is just a reminder that new releases under the latest tag might introduce errors for you. So it is recommended to stay on a working, fixed release version (tag) instead of using the latest tag. However, if you want to have instant updates and don't mind an interruption of your reverse proxy, keep using the latest tag.

**Comment by johntdavis84** [comment]
Thanks!
