### ISSUE TITLE
MIPS/MIPSel port

### ISSUE THREAD

**Issue by gatesps** [jc21/nginx-proxy-manager#1223]
**Describe the solution you'd like**
I'd like to be able to install NPM on my EdgeRouter X, which uses a MIPSel architecture.

**Describe alternatives you've considered**
There's no obvious way to install NPM by hand.

**Comment by chaptergy** [comment]
The MIPS architecture is not officially supported, and due to low demand will most likely never be. So to use it on your MIPS based device, you would have to compile the docker image for this platform yourself. If you want to do this, the [buildx](https://github.com/jc21/nginx-proxy-manager/blob/develop/scripts/buildx) script might be a good starting point.

In the further future it might become easier to run this on MIPS because of the switch to [Go](https://github.com/jc21/nginx-proxy-manager/discussions/1202) in v3.
