### ISSUE TITLE
Custom location with IP access list

### ISSUE THREAD

**Issue by lindi200000** [jc21/nginx-proxy-manager#1242]
Hello,
I have set up a default proxy host without any restrictions. 
Now I want to share the custom location /admin only for certain IP ranges.
For this I have entered the following under advance. 

location /admin {
   allow 192.168.50.0/24;
   allow 192.168.188.0/24;
   deny all;
}

But unfortunately this does not work. I am now blocked for /admin everywhere. 
Can I somehow custom locations only for certain IP ranges

**Comment by Galileon-venta** [comment]
A) this is more of an nginx config issue and not related to this project

B) your aproach seems 100% fine for me as long as the Code is injected corectly into the config file (might want to check by going into the docker containers console). The problem is propably related to your docker network Configuration.

**Comment by lindi200000** [comment]
Ok, it works now. 
I delet all from advance and go to custom location.
![image](https://user-images.githubusercontent.com/16406425/125734246-0836cec7-339a-447e-b0f2-2341735c06e4.png)
