### ISSUE TITLE
Add TLS 1.3 Support

### ISSUE THREAD

**Issue by ne4u** [jc21/nginx-proxy-manager#128]
Using the latest version of alpine linux should add nginx and openssl versions that support TLS 1.3

**Comment by jessebraham** [comment]
Previously haven't had any issues, upon installing on a new machine tonight I get a `502` whenever I try to hit a proxy host. Looking in `data/logs/error.log` I found:

```
2019/05/02 02:22:47 [error] 391#391: *58 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream
```

So yeah, looks like no TLS 1.3 support and therefore new certificates from Letsencrypt will not work.

**Comment by jc21** [comment]
Ok if someone wants to test the fix here, use this docker image and let me know how you go before I move forward:

`jc21/nginx-proxy-manager:develop`

note this is an `amd64`, won't work on any raspberry pi's

**Comment by jessebraham** [comment]
That was quick! So I think I had mis-configured something, and the error message was just a bit of a red-herring. I tested your develop image (which has some CSS oddities, by the way, seems fine otherwise though) and it worked. However, I then reverted to latest and everything seems happy still, so as I said I think I had made a mistake on my end :smile:

**Comment by OhHeyAlan** [comment]
@jc21 I've been running `jc21/nginx-proxy-manager:develop` for about a week now with no problems and I modified the ssl-ciphers.conf to only allow TLSv1.2 & TLSv1.3

**Comment by jc21** [comment]
Awesome. I'll promote this to a new release
