### ISSUE TITLE
No issues, works perfectly! Cloudflare API integration?

### ISSUE THREAD

**Issue by Marixlive** [jc21/nginx-proxy-manager#144]
Hello
Thank you for this awesome Project!
Can you integrate the cloudflare api? To automatically create a cloudfalre dns entry when creating a new proxyhost? Would be so practically.

Have a nice day and greetings matthias

**Comment by OhHeyAlan** [comment]
@Marixlive BTW, since you use Cloudflare, you can generate origin certs from their dashboard that won't expire for 15 years... :-)

**Comment by sieb22** [comment]
> 
> 
> Hello
> Thank you for this awesome Project!
> Can you integrate the cloudflare api? To automatically create a cloudfalre dns entry when creating a new proxyhost? Would be so practically.
> 
> Have a nice day and greetings matthias

Also maybe to add on to that, Update the IP when the hosts IP address changes.

**Comment by jc21** [comment]
> Update the IP when the hosts IP address changes.
That would mutate this project in to a dynamic dns service.

Automatically updating DNS services for required settings is a nice idea, I can see some complications with requesting SSL at the same time as creating a DNS entry and that would fail because of race conditions.

To further the suggestion, AWS Route 53 or other DNS services could be included.

**Comment by sieb22** [comment]
> That would mutate this project in to a dynamic dns service.
Well it would be easier then doing it manually or editing a config via scripts.

**Comment by jc21** [comment]
https://github.com/jc21/nginx-proxy-manager/releases

**Comment by andriej** [comment]
How about cloudflare API so DNS-challenge for lets encrypt is possible?

**Comment by DJManuel** [comment]
Starting from V2.5.0 the support for CF DNS Challenge has been added (Thank you a lot for this feature, I really like it :) ), I think this  addition would be very good to directly create a DNS record using the CF API.
I think it should be relativly easy to use the API for that, and have a checkbox when creating a new proxy host to create a new DNS entry.
With the problem you've mentionned about the timing between creation of DNS and SSL request, It may be easy aswell to have some kind of "Task Queue" for that, so that first of all the DNS request is being created and the SSL request is in Queue and may be checked every few N-seconds / minutes until the DNS entry has been propagated.

@Marixlive Maybe Is there some specific reason for the closure of this feature request? Could it be re-opened, and probably has a more descriptive Title ("Cloudflare API Integration" is quite general, more specific title like "DNS Entry creation using CF API" or there about), Otherwise I can create a new feature request for this topic.

I would defentetly love such a feature to be implemented, however it is nothing of urgency :)
Anyhow, keep up your good and appreciated work with this project 👍

**Comment by martinkeat** [comment]
> > Update the IP when the hosts IP address changes.
> 
> That would mutate this project in to a dynamic dns service.
> 
> Automatically updating DNS services for required settings is a nice idea, I can see some complications with requesting SSL at the same time as creating a DNS entry and that would fail because of race conditions.
> 
> To further the suggestion, AWS Route 53 or other DNS services could be included.

Mutation into DDNS alongside reverse proxy wouldn't be a bad thing. Especially for those of us tearing our hair out with dynamic IP addresses. LOL - Also the idea of having cloudflare API to automatically setup origin certificates and setup the correct security settings that would be a freaking game changer.
