### ISSUE TITLE
Certs are not Auto-Renewing

### ISSUE THREAD

**Issue by pageb018** [jc21/nginx-proxy-manager#154]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
- Are you sure you're not using someone else's docker image?
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
Running latest version v2.0.13, none of my certs are auto-renewing. 

**To Reproduce**
Add proxy host. Wait for cert renew

**Expected behavior**
SSL certs should auto-renew in before expiration. 

**Screenshots**

![Screen Shot 2019-05-28 at 12 12 02 PM](https://user-images.githubusercontent.com/26354599/58493859-dc46de00-8141-11e9-8ddf-8dd8f487e178.png)

**Operating System**
- docker on CentOS 7

**Additional context**
Docker version - 18.09.6

**Comment by pageb018** [comment]
Seeing these errors in the logs...

```
"Attempting to renew cert (npm-1) from /etc/letsencrypt/renewal/npm-1.conf produced an unexpected error: Failed authorization procedure. unifi.olddogconsulting.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://*MY DOMAIN.com*/.well-known/acme-challenge/pwQ2zDae6MC0DciJ0fURqfNZS3S2YbVPXokxa-dD7Yc [100.1.234.69]: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n". Skipping.
nginx-proxy-app | All renewal attempts failed. The following certs could not be renewed:
nginx-proxy-app |   /etc/letsencrypt/live/npm-1/fullchain.pem (failure)
nginx-proxy-app | 1 renew failure(s), 0 parse failure(s)
```

**Comment by jc21** [comment]
Firstly, yes your certificates are renewing for the rest of your valid domains. If you navigate to those sites and view the SSL cert info, you'll see the expire date is different to the user interface.

When just one of the renewals fail, it doesn't continue to the next step which is to sync the dates of all the certs with the database.

The reason for one or more to fail is most likely due to a previous bug where deleting a certificate was not fully deleting it, meaning that it was attempting to renew even though the host didn't exist for it anymore.

Instructions to alleviate this broken certificate can be found in my latest comment in #109
