### ISSUE TITLE
LetsEncrypt TLS-ALPN-01 verification

### ISSUE THREAD

**Issue by kisonay** [jc21/nginx-proxy-manager#158]
is it possible to enable TLS-ALPN-01 for https verification

**Comment by KitKat31337** [comment]
Just a note for anyone else finding this.  this doesn't appear to be added to npm, and I didn't notice at first that the same user that opened the issue is also the one that closed it as complete.  Do not take this to mean that there is a way to use TLS-ALPN-01 in npm.  I have not yet found a way to do so and will have to use caddy at my house where port 80 is simply unavailable.
