### ISSUE TITLE
Error code: SSL_ERROR_NO_CYPHER_OVERLAP with CloudFlare proxy

### ISSUE THREAD

**Issue by cachho** [jc21/nginx-proxy-manager#1607]
Hi, I'm trying to use NPM as a reverse proxy on my dedicated server. The first thing I'm trying to do is setup a reverse proxy for the NPM admin area itself and protect it with SSL. I also got the same result with other sites, but I think it's easier reproducible if just talk about NPM.

When I use a CloudFlare proxy I get the following SSL error:

> Error code: SSL_ERROR_NO_CYPHER_OVERLAP

that's in firefox, but I get similar messages in other browsers.

The second I turn off cloudflare proxy I can connect.

I purged the cache on cloudflare and my local browsers. My cloudflare settings are largely default settings. I rebooted the dedicated server and my machine.

I tried all possible combinations for SSL certificates:

1. Certificate on NPM and Cloudflare
2. Let's Encrypt on NPM and OFF on Cloudflare
3. No SSL on NPM and Cloud Flare FULL SSL

Is it not possible to use cloudflare proxy and nginx proxy server at the same time?

Thanks for your help.

**Comment by chaptergy** [comment]
There are people who have Cloudflare working. However this is not for support on how to use Cloudflare, the issues here are for feature requests and bugs. That's why I will close this issue.

You have to let NPM handle the SSL and set up cloudflare so it just passes through the ssl encryption, but I can't tell you how, because I have never used cloudflare. The Reddit community is a better place to ask things like this. Or if there is a cloudflare support forum, over there. NPM is just generating configs for nginx, so you have to find out how to proxy a reverse proxy in cloudflare.

**Comment by cachho** [comment]
Appreciate the help!
