### ISSUE TITLE
Reverse proxy to url (for example Nextcloud and pihole)

### ISSUE THREAD

**Issue by geelenbert** [jc21/nginx-proxy-manager#162]
For some services i like to do reverse proxy not just to an IP and Port, but also to an additional path.

For example:
Pihole uses http://192.168.1.100/admin

Nextcloud used http://192.168.1.101/nextcloud

I would like to connect from https://pihole.domain.com and https://cloud.domain.com

my nginx configs looks like this:
`proxy_pass http://192.168.1.100/admin/`
`proxy_pass http://192.168.1.101/nextcloud/`

This works perfect. 
proxy to the ip and port forks fine, just not adding the extra admin or nextcloud.

**Comment by etricky** [comment]
+1

**Comment by modem7** [comment]
+1 also

**Comment by adamgreenberg07** [comment]
Any chance this has been solved. I'd like to access my pihole from a subdomain address and can't figure out how to configure the NPM to accomplish this. Does anyone have this working?

**Comment by asherman07** [comment]
I am having trouble with this as well but I have PiHole running on a different machine, I did find a work around is add the proxy then type the path manually ie. pihole.example.com/admin. I did thought NPM did have this built in (custom location?) but I wonder if it not working or if I'm using it incorrectly, my bet is the latter.

**Comment by chaptergy** [comment]
Yes, this works. When add a proxy host as usual without any path, then go to the _Custom Locations_ tab, and add a location `/` with your ip + path int the _Forward Hostname / IP_. But do this at your own risk, since this will most likely lead to broken links on whatever page you forward this to.

![image](https://user-images.githubusercontent.com/26956711/117734718-9034bd00-b1e3-11eb-9cff-4fb37ca829fd.png)
