### ISSUE TITLE
Multi-level subdomain

### ISSUE THREAD

**Issue by michaelwps** [jc21/nginx-proxy-manager#167]
setup a new proxy host.
nvr.fulton.example.com

going to that link it wont find the host.
i added nvr.example.com to the same host. 
going to this link works fine.

do we not support multilevel subdomains?

**Comment by der--flo** [comment]
I'm using a lot of 4th level domains in nginx-proxy-manager without problems...

**Comment by jc21** [comment]
This is just a wrapper for Nginx so it will do whatever nginx allows, I too am using `something.somehere.mydomain.com` just fine. My guess is that your DNS is not correctly configured for the FQDN.

**Comment by michaelwps** [comment]
I setup a new instance and it seems to be working.

**Comment by BoguschMedia** [comment]
**For those who have been searching for a solution to a similar problem, here's a bit of info (specific on my problem, but i hope it will help someone ;-) ):**

I encountered problems with NPM using multi-level subdomains. However, it turns out the issue isn't with NPM itself; it's the classic "**it's always DNS**" scenario. It seems that some DNS servers provided by my local internet service are having trouble with multi-level subdomains (for reasons unknown).

Furthermore, **it appears** that propagating DNS entries worldwide is a bit slower compared to standard (sub-)domains, which have only one level, so to speak.

To make matters worse, I've found many issues related to DNS in German router forums, which can be traced back to the use of Fritz!Box routers. It seems that these devices occasionally suffer from bugs.

I personally experienced a problem where, even after several days, my DNS from the internet provider "EWEtel" did not correctly output the DNS entries. Additionally, my Fritz!Box seemed to distort the response from the DNS server of EWE (and others).

**So, if you can't reach a subdomain or multi-level subdomain, try to troubleshoot your DNS using tools like nslookup or online services such as [dnschecker.org](https://dnschecker.org/).**
