### ISSUE TITLE
Domain to Service

### ISSUE THREAD

**Issue by FurJorden** [jc21/nginx-proxy-manager#1674]
Hello,

Is it possible to redirect an incoming domain for a Minecraft server like Test.domain.com:25565 to an internal ip like 192.168.2.15:25585?

With kind regards

**Comment by chaptergy** [comment]
Yes and no. Routing based on the domain is only available for HTTP protocols or protocols which include SNI information, and not for TCP or UDP streams. Minecraft uses its own protocol based on TCP and does not include any SNI info. However routing based on ports is available. As long as you don't want multiple domains on port `25565`, you can just use the port and ignore the domain (as long as the domain points to your npm instance). To do that you can create a stream host for port `25565` and forward it to your minecraft server (don't forget to expose port `25565` in your docker-compose as well).

More advanced routing like forwarding `mc1.example.com:25565` to `1.2.3.4:25565` and `mc2.example.com:25565` to `5.6.7.8:25565` is not possible for the reasons described above.

**Comment by operinko** [comment]
You'd be better off using SRV records to point different MC domains to certain ports.
So: 
`_minecraft._tcp.name TTL class SRV priority weight port target`

Example:
`_minecraft._tcp.server 30 0 5 25585 server.example.com`

That effectively makes it so that if you put in "server.example.com" in your Minecraft client, it looks up the SRV record and fetches the port from that (25585 in this case), without the need to specify it in the address field.
