### ISSUE TITLE
Dashboard incorrect number of hosts

### ISSUE THREAD

**Issue by jayjupdhig** [jc21/nginx-proxy-manager#1679]
![1](https://user-images.githubusercontent.com/42765391/147343190-879988ea-ac78-4599-ac94-1df0dfc29d38.jpg)
![2](https://user-images.githubusercontent.com/42765391/147343193-ad4f5476-6d24-4467-afbf-32dfec767f99.jpg)

**Comment by chaptergy** [comment]
So just the dashboard shows 0, but when you go to the proxy hosts list everything is correct?

**Comment by jayjupdhig** [comment]
yes. seems so.

**Comment by chaptergy** [comment]
Have a look at your browsers developer console, whether it shows anything that could be helpful. Also have a look at the network tab in your browsers developer console when refreshing the page. It should contain a network request with file name `hosts`, and if you click on it you should see it is a request to `<domain>/api/reports/hosts`. What is the response of this request?

**Comment by jayjupdhig** [comment]
Before holidays, i updated it via apt update && apt upgrade... now i came back and wanted to to i again.

but now i see that ALL space on my ~30gb VM HD is used:

![image](https://user-images.githubusercontent.com/42765391/147913910-00d6ede5-527e-43b5-b395-29539fb2a6e0.png)



when i enter df i get that:

![image](https://user-images.githubusercontent.com/42765391/147913942-23aba9cb-4319-422a-8e0a-cfd0dafe3bf7.png)


I don't no what this is... 

- Maybe the log files?

- Which is /var/lib/docker/overlay2/c52a5ad4ec466b99391ce1cb4d5227ff32f215473602df5a722be35be7ea48fa/merged which needs 100% ??

- Maybe the server was hacked? (has no ssh connetion to port 22 in public internet)

**Comment by jayjupdhig** [comment]
Is your product using log4j? Was i hacked!?!?

**Comment by chaptergy** [comment]
No, nothing used by npm is Java-based so it has nothing to do with log4j. So if you were actually compromised it was most likely due to weak passwords, an insecurely set up server or (though unlikely) due to some unknown vulnerability.  
But must likely you weren't hacked. Is there a specific file which is that large? It could be the logs. It so, you would have to create your own [logrotate](https://linux.die.net/man/8/logrotate) config and [mount it into the container](https://github.com/jc21/nginx-proxy-manager/issues/1317#issuecomment-898376878). Also have a look at the [original logrotate config](https://github.com/jc21/nginx-proxy-manager/blob/develop/docker/rootfs/etc/logrotate.d/nginx-proxy-manager) to see how it is set up by default, and what you can change to have the log files deleted earlier.

**Comment by jayjupdhig** [comment]
Makes no sense in investigate close before the "off-topic"-Problem is solved...

**Comment by jayjupdhig** [comment]
I also startet a new installation with must current versions (debian , docker, mariadb), but there fails something with db condig in yml file: https://github.com/jc21/nginx-proxy-manager/issues/1720

**Comment by jayjupdhig** [comment]
...

**Comment by jayjupdhig** [comment]
closed wrongly - now opend again ;-)

**Comment by jayjupdhig** [comment]
closed

**Comment by jayjupdhig** [comment]
What i see is that when i open developer tools then do a browser refresh:


![image](https://user-images.githubusercontent.com/42765391/148236402-128156cd-0647-47c0-a989-452b272517e4.png)

**Comment by jayjupdhig** [comment]
...but nothing with /api/reports/hosts: 

![image](https://user-images.githubusercontent.com/42765391/148236570-8e531e8e-e05a-4cdb-ba48-222dcef22a2f.png)

**Comment by jayjupdhig** [comment]
[complete new installation with debian 11 as described above.. ]

**Comment by jayjupdhig** [comment]
After adding one (1) "HTTP only" i see:

![image](https://user-images.githubusercontent.com/42765391/148237327-f6408bf9-a657-4cc1-8c07-cfc88de66030.png)


Does this only work if http instead of https...? Strange..

**Comment by chaptergy** [comment]
Were your screenshots from the network tab taken after the dashboard was loaded while the network tab was open? Because it seems the proxy host page was loaded, not the dashboard.

So it does work for http only hosts, but it is still not counting the https hosts? Or have you only tried http only hosts?

**Comment by jayjupdhig** [comment]
1. Visited page
2. Called dev tools
3. Refreshed the page

So it does work for http only hosts, but it is still not counting the https hosts?

Yes.

Or have you only tried http only hosts?

No. I have 4 https and 1 http host

**Comment by chaptergy** [comment]
Hm, I'm really not able to replicate it, no matter what combination of https and http hosts I have.

What database are you using? MySQL or SQLite?

**Comment by jayjupdhig** [comment]
SQLite

**Comment by jayjupdhig** [comment]
Shift-F5 for browser refresh (bypass cache in chrome / chromium [so also edge] engine based rowsers) does also not show all 5 hosts on main (entry) page

**Comment by chaptergy** [comment]
Hm, then I'm really at a loss here, I have no clue what might cause something like this

**Comment by jayjupdhig** [comment]
anyway..

**Comment by jayjupdhig** [comment]
Another question HERE: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1736
