### ISSUE TITLE
GOOGLE DNS

### ISSUE THREAD

**Issue by jeffryjdelarosa** [jc21/nginx-proxy-manager#1681]
**What provider would you like to see added to NPM?**

Google

**Have you checked if a certbot plugin exists?**

I have problem with PRIVATE KEY, it has problem wiht Invalid control character at: line 5 column 46 (char 182).

**Comment by mcowger** [comment]
I'm seeing the same behavior.  The same credential file works fine on certbot 1.22.0 on my laptop.

**Comment by chaptergy** [comment]
I have just checked, the json string should be saved to file exactly as provided. What character is in line 5 column 46 (char 182)? So what character is causing this? Maybe this could have something to do with https://github.com/jc21/nginx-proxy-manager/pull/1697, but since you said your image runs with certbot 1.22.0, which is the newest version, this shouldn't be the case.

**Comment by jeffryjdelarosa** [comment]
The character is /n then I replaced it for //n, then it jumped to the next /n, so what I did was replaced them all. After It takes some time and I got an error when I look at the logs it said the _acme txt is not correct.

**Comment by jeffryjdelarosa** [comment]
Nice !
