### ISSUE TITLE
How to redirect www to non-www (or non-www to www)?

### ISSUE THREAD

**Issue by purk4** [jc21/nginx-proxy-manager#1684]
Is it possible to redirect www to non-www?

I have everything up and running, but there are no option to redirect www to non-www or vice versa.
It is not good for SEO perspective if both https://www.example.com and https://example.com are accessible.

Does anybody know the solution for this?

**Comment by ch4ox** [comment]
That's what "Redirection Hosts" are for 😉

Example: You want to have everything redirect to www.example.org:
- Set up a "Proxy Host" which only covers www.example.org
- Set up a "Redirection Host" with HTTP code 301 which covers example.org and *.example.org and forwards to https://www.example.org (make sure to tick "Preserve Path")

Example: You want to have everything redirect to example.org:
- Set up a "Proxy Host" which only covers example.org
- Set up a "Redirection Host" with HTTP code 301 which covers *.example.org and forwards to https://example.org (make sure to tick "Preserve Path")

The important thing to know is that "Proxy Hosts" always have priority, that's why you can have a "Redirection Host" with *.example.org and it won't cover www.example.org if there's already a Proxy Host for that. 

BTW: If you tick "Force SSL" on your "Proxy Host" there will be a redirect to HTTPS as well.
