### ISSUE TITLE
Add entity ids to tables in web interface

### ISSUE THREAD

**Issue by Kranzy** [jc21/nginx-proxy-manager#174]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
**Yes**
- Are you sure you're not using someone else's docker image?
**Yes**
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
**Yes**

**Describe the bug**
- What version of Nginx Proxy Manager is reported on the login page? **Nginx Proxy Manager v2.0.13**

When creating a proxy with new SSL Cert it seems to be placing the cert files in the `/letsencrypt/archive/npm-3` folder instead of the `/letsencrypt/live/npm-3` folder. Also is there any way to know which npm- folder belongs to which proxy?

**To Reproduce**
1. Setup new proxy with new ssl cert
2. navigate folders to find ssl cert files

**Expected behavior**
I expected to find the files in this location  `/letsencrypt/live/npm-3`  but instead of npm- it would be the proxy name or another identifiable name

**Operating System**
- Running on docker on Synology Nas

**Comment by qy2009** [comment]
totally agree, if the folder can represent the proxy name, would be much easier!

**Comment by smootjenl** [comment]
+1 using NGINX proxy manager for homeassistant, so i need to know the location of the certs for using the cert in for other plugins for example. also for using the cert on other machine for tunneling ssl trough the proxy.

**Comment by jc21** [comment]
> totally agree, if the folder can represent the proxy name, would be much easier!

The problem here is that a cert can have multiple domain names, even wildcards. In addition, a cert can be applied to more than 1 proxy host, redirection host etc. So it made sense to keep it numerical as far as `certbot` is concerned.

As for the `archive` vs `live` folders, this is a `certbot` thing that I don't have control over. I believe the `live` folder has symlinks to the archive one.

**Comment by Kranzy** [comment]
that makes sense in terms of multiple names per cert etc. Is there a way in your front end to note the corrosponding folder for that particular cert, at least that way we know which one to use?

**Comment by jc21** [comment]
Yeah so this would as easy as adding an ID column to all the objects. I myself have been wanting to do it when I'm debugging stuff :)

**Comment by miguelwill** [comment]
that's right, in other hosting panels (like ispconfig) the site ID appears in the first column, allowing you to know in the list itself which ID corresponds to the site you need
for the certificates you could have the same solution, so you could have the ID at hand in case of automating the extraction or copy of the certificate

**Comment by jonas-resch** [comment]
You could also use the timestamp to check which certificate is stored in which folder. Just use the creation date and expiration time displayed in the web ui under "SSL certificates"

**Comment by kennylajara** [comment]
+1 Waiting for this.

**Comment by kennylajara** [comment]
I think that a good option is to add a file named `hosts.txt` or something similar inside of the `/letsencrypt/live/npm-#` where you can find a list of the hosts having this SSL.

But, in the mean time, how can I know what number is each SSL?

**Comment by chaptergy** [comment]
Unfortunately I can't think of any way this is currently possible. However I just opened a PR for this. But instead of txt files or a new table column I have opted to put this information inside the three-dot-menu on the right. (This is because this is only relevant for few people, so it shouldn't need a prominent place.)

![image](https://user-images.githubusercontent.com/26956711/118401962-415dac00-b657-11eb-9aff-680cd9a05a49.png)

In a while an automatically bult docker image should be available under `jc21/nginx-proxy-manager:github-pr-1100`, which you can use before it is merged and a new version has been published.
