### ISSUE TITLE
What is the admin URL?

### ISSUE THREAD

**Issue by Daemach** [jc21/nginx-proxy-manager#199]
I did docker-compose up and waited for something to happen.  Went to 127.0.0.1 and got this:  https://www.screencast.com/t/spSzAm4Fb  (making the words admin panel a link would be most useful)

127.0.0.1:81 (admin port from docker compose) said connection reset.

Running docker-compose up without -d yields this:  https://www.screencast.com/t/YoNCnL0cr1  Maybe there is an error?

Looking forward to trying this - looks great from the screenshots!

**Comment by jc21** [comment]
Looks like your DB isn't initializing. What docker image are you using for it?

**Comment by dzikus** [comment]
For other google users: Admin Panel URL is http://npm_ip:81

Why this is closed without resolution? I'm reading docs and also don't know what is admin panel url (In docs there is a lack of this info!!!) ! It's insane to relay on such basic information and not provide it.

**Comment by chaptergy** [comment]
The admin panel port is documented in both the [quick setup](https://nginxproxymanager.com/guide/#quick-setup) in step 4 and in the docker container logs when starting the image. Though we can add even more information about that.

The actual issue also had nothing to do with the title, it was about the database connection not working, and it was opened a while ago, and a lot has changed since then. Also there were no further responses, thus it was closed.
