### ISSUE TITLE
Thank you and my suggestions for the future. . .

### ISSUE THREAD

**Issue by PsychedelicHell** [jc21/nginx-proxy-manager#262]
Firstly I want to say thank you for making such an easy (once it's running) and life changing (seriously!) piece of software. I had tried TygerCaddy, Tyger2, Ajenti V and Traefik and I'd either not finish installing them at all (dependencies galore) or I'd get in and (due to an extreme lack of tutorials) have no idea what I'm doing (like with Tyger2). I was about to give up and go back to the standard Nginx on Ubuntu server and again have to deal with 'sudo nano' and config files.

Then I stumbled upon your solution; at first I cringed at needing to use docker, but those screenshots you posted are what made me try and after about an hour of trying I got docker running on a Ubuntu Server VM and booted into Nginx Proxy Manager.

After playing around with docker and reinstalling Nginx Manager half a dozen times (for some reason I couldn't open the admin panel on port 81. It just wouldn't load for me)

I messed around with the settings and got everything working, for a while I couldn't figure out why I was getting 502 errors but once I changed the forward port from 80 to 443 everything instantly worked! My pages load FAST with full SSL.

Thank you so so much for this software, it's amazing. It will be so helpful to me I would pay if it wasn't free.

The only suggestion I can place for the future is a **super noob friendly install**, one or two line entries that push and unpack everything that just ends with a "install complete, navigate to IP in your browser) and perhaps more in-depth wiki (I'd even be happy to contribute now that I've got my one working)

I am currently running on a VM but in the future I'd like to use a spare Rpi Zero. Would this be powerful enough? Does the Nginx proxy actually process traffic or just direct it? I ask as I have a NextCloud set up and I'm not sure if a Rpi3 proxy would bottleneck or not.

Hopefully the Rpi 3 would be perfect for this project and I can move from my VM to it in the future, but I think I'll wait for a better tutorial before I try that!

Thank you again jc21

**Comment by jc21** [comment]
Thanks for the praise and feedback!

Making a noob friendly install process is definitely my goal, which is why I build as a docker image in the first place, but yes I can understand the concept of containerization is new to most.

Since this project only configures Nginx and doesn't touch proxied data, all the processing is contained within Nginx.

Off the top of my head I would assume that a Zero would not be powerful enough probably from a lack of memory, but a Rpi3 is definitely fine. If you use HomeAssistant (Hass.io) you can also install this project as an addon. There haven't been any bug reports about an upstream service that failed due to hardware limitations on the NPM side.

Although using this project on a Rpi3 would be fine, I'm a power user and I run about 40 sites on my home network - and I run NPM on a more powerful machine purely to get the extra (arguably negligible) speed.

Glad you like it so far. Feel free to watch this project for Releases :)

**Comment by PsychedelicHell** [comment]
Hahahaha of course there is a 2 click solution!

Yes I use HASSIO, running it via docker on Raspbian Lite on my Rpi3 with USB boot so no more corrupt SD cards!!

Thanks a lot dude, can't believe I didn't see this in the HASSIO addons, been using the software for years. You've made some beautiful software, thank you so much.

Nginx Proxy Manager will be a permement addition to my HASSIO system, cheers.
