### ISSUE TITLE
Make the nginx reload interval configurable

### ISSUE THREAD

**Issue by seanGreenhow** [jc21/nginx-proxy-manager#306]
**Is your feature request related to a problem? Please describe.**
I tried using nginx to map a stream port for a game server (probably not the use-case but i think that is not relevant to the problem). 
Every hour the game clients would disconnect, at which time the server logs "ℹ  info      Reloading Nginx". After some searching i found the reload interval is hardcoded into the server. 
I am not sure if the streams need to be closed for this or if its some kind of bug, but being able to configure the interval would probably be a nice addition either way. 

**Describe the solution you'd like**
I would like to be able to set the interval after which nginx reloads the config, maybe inside the config.json ?

**Describe alternatives you've considered**
I could always map the ports through something else, but it would be great to be able to do it in nginx too, since it would allow me to manage all port related things in one place :)

**Comment by jc21** [comment]
So the 1 hour thing is actually because of other behaviour. With the SSL certificates, each hour the program will run a command to automatically renew any certs close to expiry. Then the program will `gracefully` reload nginx. I would have thought that this reload wouldn't be closing established connections, but I'd have to investigate the documentation on streams for that.

I don't think I can get away with not reloading nginx all the time. Any changes to any configuration require it.

**Comment by seanGreenhow** [comment]
I have switched to direct port forwarding for now. Maybe i'll look at the code and try some things when i have got some spare time.
Anyway thanks for the answer and this project!

**Comment by mkaulfers** [comment]
Just want to confirm that I'm also facing this issue w/ the streams functionality in NGINX-pm. I have a game server running on a port, 5049, which is forwarded from an external port of 34197. Every hour, after NGINX proxy manager restart, on the XX:34th minute, the server will kick everyone connected. There is no SSL on the stream-service, obviously, but I did confirm this to be the cause of the disconnect. Is there anything that I can do to resolve this? I don't believe it's "Gracefully" restarting lol.
