### ISSUE TITLE
Development environment running issues

### ISSUE THREAD

**Issue by sh4444dow** [jc21/nginx-proxy-manager#35]
Hey @jc21,

I'm trying to run `docker-compose` in development mode from JetBrains WebStorm IDE with exactly `nginx-proxy-manager/bin/build-dev` script meant for that purpose I suppose. I'm running `docker-compose` command from Docker for Windows in "linux containers" mode. As you may know, the `bcrypt_lib.node` contained in `nodes_modules/bcrypt/lib/` is OS dependent, and all modules in `node_modules` are compiled with windows, and due to `.:/app` volume binding configuration in docker compose, the folder `node_modules` effectively compiled in windows is now in linux app container, and also contains an invalid bcrypt_lib.node, illisible by linux (Please see [this link](https://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app) for more details about the problem).

I tried to switch docker for windows into "windows containers" mode, but docker-compose for windows version is too old (1.22, expected 1.24).

I finally tried to run into an ubuntu 18.04.1 VM, and the `nginx-proxy-manager/bin/build-dev` throws a third another error which is a weird thing like `cannot find module '../'`.

Can you please tell me in what environment you managed to run `nginx-proxy-manager/bin/build-dev` please ? I'm will try to do pull request about various enhancement and bugfixes, but it will be so good wether I could run it in development mode x)

## My windows environment
WebStorm IDE version : 11.0.1
Docker 18.09.0
Docker compose 1.23.1
Docker Machine 0.16.0
Kitematic 0.17.5
Linux Kernel 4.9.125

Sincerely,

@sh4444dow

**Comment by jc21** [comment]
Glad to see somone is interested in developing too :)

First, I don't actually use the `bin/build-dev` script, I tried to get webpack hotloading working and I don't think it's quite right. So I use `bin/build` instead - if that one doesn't work, `build-dev` definitely won't.

Next, yes because you need the packages that are specific for the container using them, you have to delete your existing `node_modules` folder and then run `bin/yarn install` which will run yarn _inside_ the same docker container that's going to use the node packages.

Let me know how you go.

**Comment by sh4444dow** [comment]
I'll try to do that tonight =) That being said, have you managed to enable hot reload on backend and frontend in the same time ? Is this the role of `yarn` actually ?

Sincerely,

@sh4444dow

**Comment by jc21** [comment]
Reopen if you are still having issues.
