### ISSUE TITLE
Access list with more then 4 ip addresses?

### ISSUE THREAD

**Issue by Magikarplvl4** [jc21/nginx-proxy-manager#432]
**Checklist**
- Please read the [setup instructions](https://nginxproxymanager.com/setup/)
- Please read the [FAQ](https://nginxproxymanager.com/faq/)

**What is troubling you?**

I'm busy with creating a Access List with a lot of ip address.
I was wondering if its possible to add more then 4 ip address?
i can't find a option todo this in the web viewer :(

_Clear and concise description of what you're trying to do and what isn't working for you_

**Comment by cmitz** [comment]
Maybe this will help you: you can also specify an ip-range instead of a singular ip-address.

For example, using `192.168.1.1/24` means all addresses between `192.168.1.1` and 192.168.1.255`. This is definitely not beginner-level network management, so you could use this tool for example: http://jodies.de/ipcalc?host=192.168.1.1&mask1=24&mask2= . Note the `hostMin` and `hostMax` values, and ignore subnet for now.

p.s. I've written this down in a way that everyone should be able to understand it. However, if you are offended that I've _dumbed this down_ too much, then sorry ;-)

p.p.s The feature request of adding more than 4 addresses/ranges is still a valid request, so this issue should stay opened :)

**Comment by PotatoQuality** [comment]
Hi @cmitz first of all: Thanks for you reply and help!

Maybe someone can use this to:
I created a workaround, i include a secondary file that include some more ip rullings.

step 1: Create a subfolder called custom_whitelist in the appdata/NginxProxyManager folder.
step 2: create a empty file called: whitelist.conf
step 3: Open nginx proxy manger, and Edit Proxy Host. Choose advanced, and place the following text: 

#include ip whitelist
include container/path/to/file/whitelist.conf;

(in my case it is: include /config/custom_whitelist/whitelist.conf;)

step 4: Open the whitelist.conf file with notepad++ or something else and write down all the ip addresses you like that can enter the subdomain/domain of what ever in the following format:

#whitelist of ip addresses
allow 192.168.0.1; #reference
allow 192.168.0.2; #reference
#block evertying else what isn't on the whitelist.
deny all; #do not change

**Comment by cmitz** [comment]
That will definitely work as well. Be careful that it might not work well **together** with the access-list since the order of defined rules is very important to Nginx

btw @PotatoQuality could you wrap the code in your comment with backticks? (`)
That'd be easier to read

**Comment by Kenchava** [comment]
Yes please!!!! I have a list of various public IPs (5-25) for various hosts and being able to define them directly into an access list instead of separate configs and including them manually would be legendary! Perhaps instead of the default interface with 4 options there is a new row of textboxes that appear or a plus button to add an additional row manually would be awesome.

**Comment by seanfromhm** [comment]
I really support this, at the moment we are using the custom config but with access lists we could add and remove items on a global level rather than one by one.

**Comment by chaptergy** [comment]
Any amount of IPs are now possible:

![image](https://user-images.githubusercontent.com/26956711/117885878-f0883500-b29d-11eb-97c1-88b1ffe7e82c.png)

**Comment by Kenchava** [comment]
I've been checking in on this every now and then and am so happy that this was added. Thank you so much.
