### ISSUE TITLE
Bug in handling localhost

### ISSUE THREAD

**Issue by MartinKuhl** [jc21/nginx-proxy-manager#445]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
- Are you sure you're not using someone else's docker image?
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? check

**Describe the bug**
- What version of Nginx Proxy Manager is reported on the login page: 2.3.0
- I have several local services running e.g. 127.0.0.1:8001, 127.0.0.1:8002 and so on and want to organise them by subdomains of the localhost address (app1.localhost, app2.localhost etc.)
But when I'm following the http:/app1.localhost/ I get the 502 error message.

**To Reproduce**
1. Go to Edit Proxy Host
2. Enter app1.localhost as Domain Names
3. Scheme: http
4. IP: 127.0.0.1
5. Port: 8001
6. See error

**Expected behavior**
openenig the the link  http:/app1.localhost/

**Screenshots**
![image](https://user-images.githubusercontent.com/55736453/83641931-7c81df00-a5ae-11ea-9386-38a6c9f12b5c.png)

**Operating System**
Docker for Windows

**Comment by theraw** [comment]
i don't see any kind of error.

You should learn read more and understand that

1. In order to reach `app1.localhost` you have to add docker container ip into your 'hosts' and not `127.0.0.1 app1.localhost`
2. you should also add it on your hosts on docker container
3. you should make sure that 127.0.0.1:8001 reaches your application so try `curl http://127.0.0.1:8001`  from inside nginx-proxy-manager container.

**Comment by MartinKuhl** [comment]
I have to edit the host file

**Comment by hgareeballa** [comment]
I have the same issue !
i can only access services using public ip,, but not with local host

note that i can crul these services with no issues using command line !
