### ISSUE TITLE
Custom SSL certificate support

### ISSUE THREAD

**Issue by kanjusei** [jc21/nginx-proxy-manager#47]
Hello, I saw in the list of options of the project "Nginx proxy manager", that you could install custom certificates.
I saw a folder in the data folder that had a name "custom ssl", I tried to upload the certificates to this place.
I had no effect on the web interface ( I also read the issues on custom certificates, but I'm not advanced, how to install them) 
 I do not know where and how to install them?

**Comment by jc21** [comment]
1. Using the Web interface, go to the Certificates menu item
2. Find the `Add SSL Certificate` button in the top right
3. Select `Custom` from the dropdown.

![custom](https://user-images.githubusercontent.com/1518257/50865490-a94db900-13f1-11e9-9f2c-68bc8276fc37.png)

Let me know if you have more issues here otherwise close the issue if you manage to get it working :)

**Comment by kanjusei** [comment]
thanks, i found . 👍
