### ISSUE TITLE
Not passing letsencrypt requests through proxy_host

### ISSUE THREAD

**Issue by xorinzor** [jc21/nginx-proxy-manager#51]
From my own testing it seems that the /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf rules prevents access to the letsencrypt tokens/acme-challenges of any hosts configured as proxy_host.

This is probably because it's trying to access it's own letsencrypt challenges, which ofcourse isn't going to work.

If this isn't something that can be fixed to be allowed for proxy_hosts, can it be disabled in the meanwhile?
It will currently prevent my services of renewing it's certificate when the Nginx-proxy-manager docker container is going to update (and I forget to "fix"/disable the letsencrypt rules). 

Alternatively, a way of making these config files persistent would be great too.

**EDIT:** I just noticed that doing this prevents the proxy-manager from  updating it's letsencrypt certificates..

**Comment by xorinzor** [comment]
I've been trying to adjust the config file myself, to check if the requested file exists locally before using proxy_pass. But for some reason I can't properly test it because it will always return a 404 on a file that I put in the /config/letsencrypt-acme-challenge directory. Even with the default config file source.

Double checked the permissions too. Almost feel like there's something else going on whenever the nginx-manager updates the certificate.

Would very much appreciate it if you could realize this.

**Comment by jc21** [comment]
The project was not designed for people who want 2 or more letsencrypt services on their network.

We need to capture all acme requests because there may be hosts in the project that are disabled or deleted, but their Certificates still exist and get automatically renewed.

I don't know the reasons for you to want multiple SSL terminated services on the same IP but this project might not be for you if that is a requirement.

**Comment by xorinzor** [comment]
The reason I want multiple SSL is because the proxy manager only uses SSL to be able to proxy https requests too.

However, the services that run behind the web interface will still need their own certificates renewed to be properly used (ie: poste.io mailserver).

IMO hosts that are disabled or deleted shouldn't be managed by the proxy manager, active hosts should take priority, and the requests should be passed on if they aren't meant for the proxy manager.

**Comment by xorinzor** [comment]
For the moment I fixed this for me by configuring it to HTTP only, given that I block pretty much everything except letsencrypt for this particular service at this moment.

I still stand by my previous point though.

**Comment by vibratim** [comment]
I am trying exactly the same atm. My poste.io mailserver needs to create its own certificate via Let's Encrypt (which kind of worked with a custom location for the mailserver entry) and if this works the http/s would not get through. 
Option 2 is giving the poste.io container the certificate files, but i am not sure where to find them etc.

**Comment by george-viaud** [comment]
I have the same issue with needing letsencrypt to generate a cert on my poste.io install.  Alternatively, if the poste.io instance could somehow fetch the cert from nginx proxy manager, or if the letsencrypt could be

**Comment by hmic** [comment]
I too think that this is a valid request. As of today there are plenty of services that do need to handle their own certificates in addition to https use. Many are using letsencrypt which fails badly behind NPM without good reason. As stated, it should be easy to pass through missed requests if the file requested is not from NPMs ACME client. If you think it could interfere with disabled hosts - which I as well think should be let alone with no renewal happening until they are activated again - just make it an option to enable in the proxy-host configuration.

I would be happy with a config snippet to use in my installation/proxy-host config that forwards the request if the file is not found for the NPM ACME client. Anyone?

Thanks guys!

**Comment by Grolaf** [comment]
Hi There ! 

I'm also using services that are handling their own certificates behind my NPM (such as mailcow, another mail service).

The only solutions I had were :

- to manually copy my proxy host's SSL certificates to the service itself or....
- to switch back to apache

 and I chose this latest option because I do not want to manually copy the cert each time the cert is renewed or to automate it (which can basically add vulnerabilities with ssh keys between VMs etc...)

After all, I really liked the project and I found it a really nice idea... But nowadays i cannot understand why a reverse proxy could not forward ACME challenges...

Thank you anyway for you nice work guys !
