### ISSUE TITLE
Shellscript upload possible via upload of 404 pages

### ISSUE THREAD

**Issue by DragonicDefson** [jc21/nginx-proxy-manager#515]
**What happened**
- My NGINX Proxy Manager installation got hacked, They've uploaded a Shellscript to affect the underlying Operating System.

**Bug Description**
- It is possible to upload Shellscript files trough the upload feature and execute them.
- All of them with the upload capability.

**Behaviour**
- Depends on the uploaded script.

**Operating System**
- Ubuntu 18.04 LTS

**Comment by raffieyeah** [comment]
@jc21 do you have any feedback on this issue?

**Comment by DragonicDefson** [comment]
@raffieyeah I don't have any more details or logs, because i had root login enabled (no other accounts) so they disabled SSH as well for my IP, had to reset the server which as well took away all logs, but i'm really sure it was a shell script.

An way to protect for this is parsing the inserted code the right way before using it as a 404 page.
If it happens again i will report back to you guys.

also, i'm modifying the proxy manager with custom logo's for my company. i don't know if i'm allowed to do this
but i wanted you guys to know this.

**Comment by chaptergy** [comment]
The only upload there is, is the certificate upload, and generally everything (even the api) is only available for logged in users. If you could upload 404 pages back then, it seems like this was removed, so this issue is no longer relevant. And if the underlying OS was affected, this sounds like an issue with docker, as it is responsible for the isolation.
