### ISSUE TITLE
Can't access any port on my server, Error 502

### ISSUE THREAD

**Issue by Stiv1100001** [jc21/nginx-proxy-manager#621]
**Checklist**

- [X] Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?

- [X] Are you sure you're not using someone else's docker image?

- [X] If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
Ports 80, 81, 443 are open and accessible. If I proxy mydomain.com to localhost:81 works fine, but if I use it to proxy to port 300, 8080, ecc. where there is a nuxt project switched on, I get a 502 error page
Nginx Proxy Manager version: V2.5.0

**To Reproduce**
I didn't do anything strange, only access to Software via login, add new proxy host with SSL Certificates (made by Nginx Proxy Manager). 
Config are:
- HTTP
- localhost
- 8080
- Cache assets
- Block Common Exploits
- WebSocket support
- Under SSL: Force SSL

**Expected behavior**
I can proxy request to any port.

**Operating System**
- Debian 10

**Additional context**
- Docker version: 19.03.13
- Docker compose version: 1.27.4

**Comment by GEkuL** [comment]
Hi
Did you work with your firewall?

**Comment by DieserMerlin** [comment]
This is because localhost refers to the container, not the host. If you proxy your content to port 81, it uses port 81 of the container (which is the proxy-manager interface).

To get it working with ports on your host machine, you need to set the proxy-manager into host-networking-mode: https://docs.docker.com/network/host/

Remember that if you do that, you cannot use the docker bridge networking to reverse proxy a domain to a container-name. Instead, you will need to define the local ip of the container.

Another solution might be to not use localhost but the IP of the host machine (no need to put the proxy-manager into host networking mode this way).
