### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by dugaa95** [jc21/nginx-proxy-manager#639]
Hi,

i habe Problem with domain certifikat, i can not make certifikat, when i try to make certifikat i have error 
**Internal Error**
But it is only for one Domain.
I make this Domain 2 3 times and i deleted, i wanted to make one test and now it not going more.
With other Domain it all ok.
Can someone help me pleas!

**Comment by thomaslc66** [comment]
Hello,

I have the same problem as you. 
When I try to change my SSL certificate I have an error, the same happens when I try to renew it as there is no feature to auto-renew it. Always an internal error with no log nothing to help.

Does anyone else is experiencing the same kind of behavior?
Thank you.

**Comment by Mickroz** [comment]
yes the same here, for some reason the certificate points to localhost when visiting the site.
