### ISSUE TITLE
Configure NPM to not interrupt downloads at 1GB

### ISSUE THREAD

**Issue by dr460nf1r3** [jc21/nginx-proxy-manager#643]
Hello, 
Im currently trying to get downloads over 1GB working via nginx. 
Im using an nginx container proxied by npm which has a custom nginx.conf mounted containing proxy_max_temp_file_size 0; (required to solve the issue) however this does not seem to work, downloads are still getting interrupted. So suspect it has something to do with npm. 
How can I change configuration to not interrupt downloads at 1GB?

**Comment by AlpixTM** [comment]
Same problem here, is there a known fix to that?

**Comment by ltonn02** [comment]
I'm having the same problem... has anyone found a solution?

**Comment by dr460nf1r3** [comment]
It seems there is no real interest in providing a solution which is quite a bummer :(

**Comment by ltonn02** [comment]
Well... I read a little bit about it and go it working for me. 
All in all it seemed to be very straight forward. 
All I had to do, was to add these into the advanced section of my proxy:

`client_max_body_size 0;`
`proxy_max_temp_file_size 0;`

It should now look like this:
<img width="491" alt="Bildschirmfoto 2021-04-19 um 17 22 28" src="https://user-images.githubusercontent.com/40540600/115261349-d4c4bf80-a133-11eb-87f8-886f433dba3c.png">

I'm using the proxy for my nextcloud which is now working without any issues.
I've tried to download a 4.7GB file which worked after applying this fix.

Hope this works for you as well :)

**Comment by chaptergy** [comment]
Glad you found a solution! But this was more of an nginx issue than an NPM one, so if similar problems pop up in the future, you will probably find solutions much quicker on platforms which provide help for nginx.

**Comment by Rustymage** [comment]
Note this issue for anyone searching, it is already present and described as 'not a bug': https://trac.nginx.org/nginx/ticket/1472

**Comment by EgonHeuson** [comment]
Hello! Thank you VERY much for this solution! It helped me a lot. 
I'd have a related question if you allow me. I installed a Nextcloud AIO instance behind my NPM, and I get an error when trying to upload large files (over 1GB approx.). Are the download and upload config both linked to these variables? Do you know how I could resolve this uploading problem? I first thought it was linked to Nextcloud, but after discussing it with the devs (here: https://github.com/nextcloud/all-in-one/discussions/979) I think it's more related to NPM. Don't you think?

**Comment by ltonn02** [comment]
Hey, since posting my original config, I've run into the same problems you are describing, myself.
I'm not sure if there's anything else that I've changed, but this is my current npm config, which handles large uploads just fine:

```
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_max_temp_file_size 16384m;
client_max_body_size 0;
proxy_buffering off;
```

If it still won't work for you, I can investigate further into my system, since I remember changing a lot of variables until I finally got it running reliably.

**Comment by EgonHeuson** [comment]
@ltonn02 You rox man! I'll try this config tonight! And I'll keep you updated here :-) Thanks a lot!

**Comment by EgonHeuson** [comment]
Just a quick question. Why do you change proxy_max_temp_file_size from "0" to "16384m"?
By the way, it also was for Nextcloud on your side?

**Comment by ltonn02** [comment]
Yes, I'm using it to expose a Nextcloud docker container to the internet. The proxy_max_temp_file_size is at "16384m" because it worked that way. I must have spent days copying every config I could find from several forums onto my system until this one finally worked. It's very possible, that "0" works just fine or even better, but as they say "never change a winning team" :)

**Comment by EgonHeuson** [comment]
Fully understand what you mean! 😅 I'll try this then :-) Your first config already solved my problem when downloading files from Synology File Station.

**Comment by EgonHeuson** [comment]
Do you have other parameters defines in the other tabs of your host config by the way?

**Comment by ltonn02** [comment]
Here you can see all the configs I made inside of npm:
![Screenshot 2022-08-12 - 15 40 32@2x](https://user-images.githubusercontent.com/40540600/184366295-c08f1227-2650-4fab-8985-fcac5b61ebf0.png)
<img width="491" alt="Screenshot 2022-08-12 - 15 42 59@2x" src="https://user-images.githubusercontent.com/40540600/184366305-ac105213-1f07-441f-81c0-f5c3e1a9a93c.png">
![Screenshot 2022-08-12 - 15 43 05@2x](https://user-images.githubusercontent.com/40540600/184366308-db3c4b07-5648-4477-ab34-a0aaa82dd760.png)
<img width="489" alt="Screenshot 2022-08-12 - 15 43 24@2x" src="https://user-images.githubusercontent.com/40540600/184366311-b2dc2113-5b74-43e3-b0a0-4e2b0a098e2a.png">
:

**Comment by EgonHeuson** [comment]
Eheh so it doesn't work on my side. The solution at the beginning of the discussion seems to resolve my issue with the synology File Station download, and I therefore can download files over 1GB. :-D 
But regarding Nextcloud AIO, nope. Whether I set proxy_max_temp_file_size  to 0, 2048, 4096 or even 16384, nothing changes. I still get an error if the uploaded file is over 2GB or so. But it's a false alarm as the file is correctly uploaded and can be found in the correct folder. So I really don't know what I'm up to here...

**Comment by ltonn02** [comment]
Hey, I've spent quite some time trying to reproduce your error, but unfortunately I was not able to do so. Anyway, here are some ideas, which might help you solve your problem. (FYI: I'm not using a Synology NAS, maybe there's a problem related to that.)
1. What Browser are you using to upload the files? If you are using Google Chrome you should be alright, but maybe there's a client-side issue if you are using Safari, Firefox, ... 
2. What you describe seems like there's another config overwriting your npm config. Maybe it's worth looking into your Nextcloud server settings. (I've installed a clean Nextcloud Docker container on my System and haven't had any problems with it though)
3. Maybe it's a hardware limitation? I'm not sure how Nextcloud handles your files while they are uploaded. Maybe they are going into your ram first? If they do, your Synology NAS might not have enough ram.
4. Do you share your Nextcloud with others? If not, there may be no problem. If I understand you correctly, the files are uploaded to the right folder, and it's just the error message that shows a faulty behavior. (I understand that this is very frustrating, but it might fix itself after some updates)

**Comment by EgonHeuson** [comment]
Hello Itonn02,
Thank you VERY much for all your time spent. Actually my Nexcloud is not on my Synology. I installed it in a VM on my Proxmox Cluster. But I think the main difference lies in the fact that I installed Nextcloud **AIO** and not the classical Docker package. It uses docker but in a much more automated and packed way and I guess this is what create the issue. I talked with the developers [here](https://github.com/nextcloud/all-in-one/discussions/979), but we didn't find the source yet. They concluded that it's due to slow hardware but my Nextcloud instance is installed on a Celeron J3455 with 3 cores allocated and 8Go of DDR3 1600MHz RAM. So it seems a little bit odd... Anyway, I hope I'll find the issue someday ☺️
Thanks again anyway for all! Have a nice evening!
