### ISSUE TITLE
Option to ignore requests coming in from WAN IP and/or any hostname not registered

### ISSUE THREAD

**Issue by Saldash** [jc21/nginx-proxy-manager#83]
At the moment, I have a DDNS address that I CNAME over for various sites/services.
If I come in on the DDNS address or what ever my WAN IP address is, I get the "Default Site".

Can we have an option to turn this off entirely?
While I can easily add the DDNS address to either a 404 or redirect host, I have to manually add my WAN address each time it changes which can be inconvenient.

**Comment by ghallford** [comment]
I would second this!! I just installed it and hitting my IP (no host name) it comes up with the "Congratulations! You've successfully started the Nginx Proxy Manager.". We need to be able to turn this off please

**Comment by jc21** [comment]
Totally understand the issue and it's almost covered by #26 already.

I'm going to close this as a duplicate, but go to #26 and comment about what you want instead of the congratulations page. If we remove that entirely, then nginx will just return the first valid host in the config as the default - so that's not an option.
