### ISSUE TITLE
2 Servers 

### ISSUE THREAD

**Issue by finnie2006** [jc21/nginx-proxy-manager#981]
Hello i have 2 Rpi 4 8gb 
1 is running something on port 443 and 80
but now i want to install something on my second and that also uses 443 and 80
Can i use nginx proxy manager for 2 serparate servers?
thanks in advance

**Comment by PythonFZ** [comment]
This seems to be more of a general question and not directly related to NPM. But I'll try to answer it anyways.

If your (two) systems run on different public IPs you can run as many instances as you want.
If not you most probably have set up a port forwarding to one of your systems in your router. In that case you can not use 2 instances of NPM on 2 systems with different IPs in your network because you can only forward one service.

If you want to make sure, that if one system crashes the other one takes over you may have to do changes on the port forwarding on your router.

But it seems like you try to run an application that already uses a SSL certificate and therefore uses port 80 and 443.
The easiest way would be to use NPM on one system (with the port forwarding) and set up a proxy host pointing to the ip of the other system and letting NPM do the encryption. This is, if you trust the traffic in your local network.

The best way for your problem may be to just set it up on one system and make yourself familiar with using different ports for different applications and the general scheme of reverse proxies.
